/*
 * Copyright 2012-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var container  = require( "vertx/container" ) ;
var eb         = require( "vertx/event_bus" ) ;
var vertx      = require( "vertx" ) ;
var vertxTests = require( "vertx_tests" ) ;
var vassert    = require( "vertx_assert" ) ;

var script = this ;

function testMissingToAddress() {
  eb.send( 'test.my_mailer', {
    "from": "tim@wibble.com",
    "subject": "Congratulations on your new armadillo!",
    "body": "Dear Bob, great to here you have purchased......"
  }, function( reply ) {
    vassert.assertEquals( reply.status, 'error' ) ;
    vassert.testComplete() ;
  } )
}

function initTable( handler ) {
  eb.send( 'test.jdbc.persistor', {
    action: 'execute',
    stmt:   'CREATE TABLE IF NOT EXISTS test ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, name VARCHAR(80), age INTEGER, CONSTRAINT testid PRIMARY KEY ( id ) )'
  }, function( reply ) {
    eb.send( 'test.jdbc.persistor', {
      action: 'execute',
      stmt:   'TRUNCATE TABLE test'
    }, function( reply ) {
      handler( reply ) ;
    } ) ;
  } ) ;
}

function testRollback() {
  initTable( function() {
    eb.send( 'test.jdbc.persistor', {
      action: 'transaction'
    }, function( reply, replier ) {
      vassert.assertEquals( reply.status, 'ok' ) ;
      vassert.assertEquals( reply.result, undefined ) ;
      replier( {
        action: 'insert',
        stmt:  'INSERT INTO test( name, age ) VALUES ( ?, ? )',
        values: [ [ 'tim', 65 ], [ 'dave', 29 ], [ 'mike', 42 ] ]
      }, function( reply, replier ) {
        vassert.assertEquals( reply.status, 'ok' ) ;
        vassert.assertEquals( reply.result.length, 3, 0 ) ;
        replier( {
          action:'rollback'
        }, function( reply ) {
          vassert.assertEquals( reply.status, 'ok' ) ;
          eb.send( 'test.jdbc.persistor', {
            action: 'select',
            stmt:   'SELECT * FROM test ORDER BY age ASC'
          }, function( reply ) {
            vassert.assertEquals( reply.status, 'ok' ) ;
            vassert.assertEquals( reply.result.length, 0, 0 ) ;
            vassert.testComplete() ;
          } ) ;
        } ) ;
      } ) ;
    } ) ;
  } ) ;
}

function testCommit() {
  initTable( function() {
    eb.send( 'test.jdbc.persistor', {
      action: 'transaction'
    }, function( reply, replier ) {
      vassert.assertEquals( reply.status, 'ok' ) ;
      vassert.assertEquals( reply.result, undefined ) ;
      replier( {
        action: 'insert',
        stmt:  'INSERT INTO test( name, age ) VALUES ( ?, ? )',
        values: [ [ 'tim', 65 ], [ 'dave', 29 ], [ 'mike', 42 ] ]
      }, function( reply, replier ) {
        vassert.assertEquals( reply.status, 'ok' ) ;
        vassert.assertEquals( reply.result.length, 3, 0 ) ;
        replier( {
          action:'commit'
        }, function( reply ) {
          vassert.assertEquals( reply.status, 'ok' ) ;
          eb.send( 'test.jdbc.persistor', {
            action: 'select',
            stmt:   'SELECT * FROM test ORDER BY age ASC'
          }, function( reply ) {
            vassert.assertEquals( reply.status, 'ok' ) ;
            vassert.assertEquals( reply.result.length, 3, 0 ) ;
            vassert.assertEquals( reply.result[ 0 ].NAME, 'dave' ) ;
            vassert.assertEquals( reply.result[ 1 ].NAME, 'mike' ) ;
            vassert.assertEquals( reply.result[ 2 ].NAME, 'tim' ) ;
            vassert.testComplete() ;
          } ) ;
        } ) ;
      } ) ;
    } ) ;
  } ) ;
}

var breakerConfig = { 
  "address" : "breaker-addr",
  "max_failures" : 5,
  "call_timeout" : 10,
  "reset_time"   : 60,
  
  "circuits": {
    "io.vertx~mod-mongo-persistor~2.0.0-final" : {
      "circuitConfig": {
        "instances": 1
      },
      "modConfig": {
        "address" : "test.my_persistor",
        "host"    : "192.168.1.100",
        "port"    : 27000,
        "db_name" : "my_db"
      }
    },
    "com.bloidonia~mod-jdbc-persistor~2.1" : {
      "circuitConfig": {
        "instances": 1
      },
      "modConfig": {
        "address" : 'test.jdbc.persistor',
        "url"     : 'jdbc:hsqldb:mem:testdb?shutdown=true'
      }
    },
    "io.vertx~mod-mailer~2.0.0-final" : {
      "circuitConfig": {
        "instances": 1
      },
      "modConfig": {
        "address": "test.my_mailer",
        "host": "smtp.googlemail.com",
        "port": 465,
        "ssl": true,
        "auth": true,
        "username": "tim",
        "password": "password"
      }
    }
  }
} ;

var readyAddress = breakerConfig.address + '.ready'

var readyHandler = function( msg ) {
  if( msg.status === 'ok' ) {
    eb.unregisterHandler( readyAddress, readyHandler ) ;
    vertxTests.startTests( script ) ;
  }
} ;

// This will get called when the circuit breaker is
eb.registerHandler( readyAddress, readyHandler ) ;

container.deployModule( java.lang.System.getProperty( 'vertx.modulename' ), breakerConfig, 1, function( err, deployId ) {
  if (err != null) {
    err.printStackTrace();
  }
});
